baseURL = "https://swharden.com/csdv"
title = "C# Data Visualization"
author = "Scott W Harden"
copyright = "Copyright © 2022 - Scott W Harden"
enableInlineShortcodes = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'emacs' #https://xyproto.github.io/splash/docs/all.html
    tabWidth = 4